# This is my first dockerfile

# This image will be simple app which prints info

FROM alpine:latest

MAINTAINER Goutham Kumar <example@gmail.com>

CMD ["/bin/echo", "Welcome to Docker Image Building Process"]
